# Install apache and remove the list of packages downloaded from apt-get update
RUN yum update -y && \
yum install httpd -y && \

# Copy the website into the apache web root directory
COPY webapp /var/www/html

EXPOSE 80

CMD ["apachectl", "-D", "FOREGROUND"]
